{
    "error": "RetryError[<Future at 0x1453a5050 state=finished raised AuthenticationError>]"
}